// Each #kernel tells which function to compile; you can have many kernels

#pragma target 5.0

#pragma kernel InitParticles
#pragma kernel ClearGrid
#pragma kernel GridUpdate
#pragma kernel PartialSums
#pragma kernel MapParticles
#pragma kernel NeighborSearch
#pragma kernel ComputeDensity
#pragma kernel ComputePressure
#pragma kernel ComputeForces
#pragma kernel Update
#pragma kernel ConstraintSolver



#include "SPHkernels.cginc"
#include "SPHUtility.hlsl"
#include "FluidMaths.hlsl"
#include "BVH.cginc"
#include "structs.cginc"
#include "sph_buffers.cginc"
#include "collisions_detection.hlsl"
#include "sph_settings.cginc"
#include "integrators.cginc"
#include "boundary_handling.cginc"
#include "constraints.hlsl"



#define MAX_NEIGHBORS 100
#define GROUP_SIZE 512

interface IForce {

    float3 ComputeForce();
};



int36 BBOX_TRIANGLES;



[numthreads(GROUP_SIZE,1,1)]
void InitParticles(uint3 id: SV_DispatchThreadID)
{
    if(PARTICLES[id.x]._static == 1)
    {

        PARTICLES[id.x].radius      = PARTICLE_RADIUS;
        PARTICLES[id.x].color       = float3(0,1,0);
        PARTICLES[id.x].velocity    =-GRAVITY*5.0f;
        PARTICLES[id.x].type        = 1;
        return;
    }

    
    int3 dimensions = GetDimensions(float3(1,1,1),PARTICLE_RADIUS/2.0f);

    int x = floor(id.x/(dimensions.y*dimensions.x));
    int y = floor((id.x/dimensions.y) % dimensions.z);
    int z =  floor(id.x % dimensions.z);

    PARTICLES[id.x].radius = PARTICLE_RADIUS;
    PARTICLES[id.x].density = 1000;;

    PARTICLES[id.x].mass = ((4*pow(PARTICLE_RADIUS,3)*pi)/(NUMBER_OF_PARTICLES*3))*PARTICLES[id.x].density;

    

    PARTICLES[id.x]._static = 0;

    
    PARTICLES[id.x].position = float3(x,y,z)*PARTICLES[id.x].radius*2.0f- HALF_BOUNDSIZE;
}


[numthreads(GROUP_SIZE,1,1)]
void ClearGrid(uint3 id: SV_DispatchThreadID)
{
    // resets tracker
    CELLCOUNT[id.x] = 0;
    CELLTRACKER[id.x] = 0;
    
    //CELLCOUNT[id.x] = 0;

}

[numthreads(GROUP_SIZE,1,1)]
void GridUpdate (uint3 id: SV_DispatchThreadID)
{

    if(id.x >= NUMBER_OF_PARTICLES) return;

   
    int idCell = GetCellHash(PARTICLES[id.x].position,HALF_BOUNDSIZE,SMOOTHING_RADIUS,NUMBEROFCELLS);
    InterlockedAdd(CELLCOUNT[idCell],1u);
    PARTICLES[id.x].hash = idCell;
    PARTICLES[id.x].predictedPosition = PARTICLES[id.x].position + GRAVITY * 1/120.0f;
    
}


// DOESNT NEED TO BE GPU BASED
[numthreads(GROUP_SIZE,1,1)]
void PartialSums(uint3 id: SV_DispatchThreadID)
{
    if(id.x >= NUMBEROFCELLS) return;
    // calculate partial sums
    int idx = id.x;
    int partialSum = 0;


    
    if(idx == 0)
    {
    partialSum =CELLCOUNT[idx];
    }

    else
    {

        for(int i = 0; i <=idx;i++)
        {
            partialSum += CELLCOUNT[idx];
        }
    }
    
    CELLCOUNT[idx] = partialSum;



}

[numthreads(GROUP_SIZE,1,1)]
void MapParticles (uint3 id: SV_DispatchThreadID, uint3 localID : SV_GroupThreadID, uint3 gID: SV_GroupID)
{

   
    if(id.x >= NUMBER_OF_PARTICLES) return; 


    // Store CellID or hash for the current grid cell
    
    int idCell = PARTICLES[id.x].hash;

    
    int index = 0;
    
    
    // Increments cell tracker and cell count for the particle
    InterlockedAdd(CELLTRACKER[idCell],1,index);
    PARTICLEMAP[CELLCOUNT[idCell] - index] = id.x;
    PARTICLES[id.x].index = CELLCOUNT[idCell] - index;
    
    
    
    
    

   
    

}

[numthreads(64,1,1)]
void NeighborSearch (uint3 id: SV_DispatchThreadID)
{

    CELLTRACKER[id.x] = CELLCOUNT[id.x];
    
    
}

[numthreads(GROUP_SIZE,1,1)]
void ComputeDensity(uint3 id: SV_DispatchThreadID)
{
    // TO DO:

    // array that stores hashes to all neighbor grid cells
    // separate kernel that initializes just that for each particle

    //density directly looks into that table and loops over the particles in PARTICLEMAP
 
    

    if(id.x >= NUMBER_OF_PARTICLES) return; 

    //PARTICLES[id.x].density = 0;

    // PARTICLES[id.x].velocity += GRAVITY * 0.02f;
    // PARTICLES[id.x].position += PARTICLES[id.x].velocity * 1/120.0f;
    
    // first test only resolve particle collisions, smoothing radius therefore must be equal to size of particle
    float3 position = NormalizePosition(PARTICLES[id.x].position,HALF_BOUNDSIZE);
    //int3 cellID = IntCoord(position/SMOOTHING_RADIUS);

    
    

    

    //int idCell = GridCellID(position/SMOOTHING_RADIUS, GetDimensions(HALF_BOUNDSIZE*2,SMOOTHING_RADIUS));

  

    int    indices[27];
    int i = 0;
    float sum = 0;
   
    int3 dimensions = GetDimensions(HALF_BOUNDSIZE*2,SMOOTHING_RADIUS);
  
    bool collision = false;

    NeighborIndexData nIndices = GetNeighborCellIndices(position, dimensions,SMOOTHING_RADIUS, NUMBEROFCELLS);
    indices = nIndices.indices;
    // int3 fakePos = position*10000;
    // int step = SMOOTHING_RADIUS*10000;

    //  for(int x = fakePos.x-step; x <= fakePos.x+step ;x+=step)
    // {
    //     for(int y = fakePos.y - step; y <= fakePos.y+step ;y+=step)
    //     {
    //          for(int z = fakePos.z - step; z <= fakePos.z+step ;z+=step)
    //             {
                
                    
    //                 float3 rePos = float3(x,y,z)/10000.0f;

    //                 int3 cellID = IntCoord(rePos/SMOOTHING_RADIUS);
    //             //     if(i == 26) break;
    //                 int u = cellID.x;
    //                 int v = cellID.y;
    //                 int w = cellID.z;

    //                 u = (sign(u) == -1) ? 0:min(u,dimensions.x);
    //                 v = (sign(v) == -1) ? 0:min(v,dimensions.y);
    //                 w = (sign(w) == -1) ? 0:min(w,dimensions.z);


    //                   uint hash = (cellID.x * 92837111) ^ (cellID.y * 689287499) ^ (cellID.z * 2839923481);
    //                 int h = abs(hash) % NUMBEROFCELLS;
                    
    //                  indices[i] = h;
                    
    //                  //indices[i] = (floor(u * (dimensions.y) *(dimensions.z)) + floor(v*(dimensions.z)) + w);
    //                 i++;


    //             }
        
    //     }
    // }
     
    //  Loop Over NeighborCells
     
    for(int j = 0; j<27;j++)
    {

        
        int nCell = indices[j];
        if(nCell < 0 ) continue;
        

          
        //if(CELLTRACKER[nCell] == 0) continue;
    	
        int start = max(0,CELLCOUNT[nCell]-CELLTRACKER[nCell]);
        //int end = CELLCOUNT[nCell+1];

        
       
      
        
       
       

        int lim = min(CELLTRACKER[nCell],MAX_NEIGHBORS);
       
        for(int i = start; i<start+lim;i++)
        {

            //if(sum >= 1500) break;
            int pIDX = PARTICLEMAP[i];
            if(PARTICLES[pIDX]._static == 1) {continue;}

            
           
            
            float3 dir = PARTICLES[id.x].predictedPosition - PARTICLES[pIDX].predictedPosition;

            if(dot(dir,dir) > pow(SMOOTHING_RADIUS,1)) continue;

            float dist = sqrt(dot(dir,dir));

           
           
            if(dist > pow(SMOOTHING_RADIUS,1)) continue;
            
           

            //sum +=    WPoly6Kernel_Bindel2011(dist,SMOOTHING_RADIUS,pi);
            sum += WPoly6Kernel(dist,pow(SMOOTHING_RADIUS,1),pi);

           

          
             
            
           
           
        }


        // Check if a boundary is near
    }

    // loop over virtual particles if collision detected

    //GetDistance
    float3 edgeDst = (HALF_BOUNDSIZE - PARTICLE_RADIUS) - abs(PARTICLES[id.x].predictedPosition);

    edgeDst.x *= sign(PARTICLES[id.x].predictedPosition.x);
    edgeDst.y *= sign(PARTICLES[id.x].predictedPosition.y);
    edgeDst.z *= sign(PARTICLES[id.x].predictedPosition.z);

    // if(IsWallHit(edgeDst))
    // {
    //     for(int i = 0; i<v_ParticleNumber;i++)
    //     {
    //         float3 vPoint = TranslatePoint(vPARTICLES[i], PARTICLES[id.x].predictedPosition);

    //         float3 dstToPoint = (vPoint - PARTICLES[id.x].predictedPosition);

    //         if(     (edgeDst.x < dstToPoint.x && dstToPoint.z < SMOOTHING_RADIUS)||
    //                 (edgeDst.y < dstToPoint.y && dstToPoint.z < SMOOTHING_RADIUS)||
    //                 (edgeDst.z < dstToPoint.z && dstToPoint.z < SMOOTHING_RADIUS)){

    //                 sum += WPoly6Kernel(length(dstToPoint),pow(SMOOTHING_RADIUS,1),pi);
                    
                    
    //                 }
    //     }
    // }

      
       PARTICLES[id.x].density = sum + 0.0000001;
      


       PARTICLES[id.x].pressure = max(STIFFNESS*(PARTICLES[id.x].density - 1000),0);
 


}

[numthreads(GROUP_SIZE,1,1)]
void ComputePressure(uint3 id: SV_DispatchThreadID)
{

    if(id.x >= NUMBER_OF_PARTICLES) return;

    int idx = PARTICLEMAP[id.x];

    if(id.x >= CELLCOUNT[CELLOFINTEREST] - CELLTRACKER[CELLOFINTEREST] && id.x < CELLCOUNT[CELLOFINTEREST]) PARTICLES[idx].color = float3(0,1,0);
    
}

[numthreads(GROUP_SIZE,1,1)]
void ComputeForces(uint3 id: SV_DispatchThreadID)
{

        // Initialize Forces to 0 and reset forces on particle
        float3 pressureForce = 0;
        float3 viscosityForce = 0;

        PARTICLES[id.x].offset = float3(0,0,0);


        // Get Index for particle neighbors
        float3 position = NormalizePosition(PARTICLES[id.x].position,HALF_BOUNDSIZE);
        int3 cellID = IntCoord(position/SMOOTHING_RADIUS);
        int3 dimensions = GetDimensions(HALF_BOUNDSIZE*2,SMOOTHING_RADIUS);
         int idCell = GridCellID(position/SMOOTHING_RADIUS, GetDimensions(HALF_BOUNDSIZE*2,SMOOTHING_RADIUS));

          //if(idCell == CELLOFINTEREST) PARTICLES[id.x].color = float3(0,1,0);

        // ======= NEIGHBOR INDICES =========

        int    indices[27];
        NeighborIndexData data = GetNeighborCellIndices(position,dimensions,SMOOTHING_RADIUS,NUMBEROFCELLS);
        indices = data.indices;
    //     int i = 0;

    //      int3 fakePos = position*10000;
    // int step = SMOOTHING_RADIUS*10000;

    //  for(int x = fakePos.x-step; x <= fakePos.x+step ;x+=step)
    // {
    //     for(int y = fakePos.y - step; y <= fakePos.y+step ;y+=step)
    //     {
    //          for(int z = fakePos.z - step; z <= fakePos.z+step ;z+=step)
    //             {
                  
                  
    //               float3 rePos = float3(x,y,z)/10000.0f;

    //                 int3 cellID = IntCoord(rePos/SMOOTHING_RADIUS);
    //             //     if(i == 26) break;
    //                 int u = cellID.x;
    //                 int v = cellID.y;
    //                 int w = cellID.z;


    //                 u = (sign(u) == -1) ? 0:min(u,dimensions.x);
    //                 v = (sign(v) == -1) ? 0:min(v,dimensions.y);
    //                 w = (sign(w) == -1) ? 0:min(w,dimensions.z);

                   
              

                
    //                 uint hash = (cellID.x * 92837111) ^ (cellID.y * 689287499) ^ (cellID.z * 2839923481);
    //                 int h = abs(hash) % NUMBEROFCELLS;
    //                 indices[i] = h;
              
    //                 //indices[i] = (floor(u * (dimensions.y) *(dimensions.z)) + floor(v*(dimensions.z)) + w);
    //                 i++;

    //             }
        
    //     }
    // }



          for(int j = 0; j<27;j++)
    {

        
        int nCell = indices[j];
        if(nCell < 0) {
            
            
            //PARTICLES[id.x].color = float3(0,1,1);
            continue;}
        
        // if(nCell== CELLOFINTEREST && idCell!= CELLOFINTEREST) {
            
        //     PARTICLES[id.x].color = float3(0,0,1);
        //     }

        
    	//if(CELLTRACKER[nCell] == 0) continue;
        int start = CELLCOUNT[nCell] - CELLTRACKER[nCell];
        //int end = CELLCOUNT[nCell];

        
       
        
       
       

        int lim = min((CELLTRACKER[nCell]),MAX_NEIGHBORS);
        PARTICLES[id.x].type = lim;


        for(int i = start; i<start+lim;i++)
        {
            
            uint pIDX = PARTICLEMAP[i];

            
        
            if(pIDX == id.x || PARTICLES[pIDX]._static == 1 ) 
            
            {

                
               
                continue;

            }
            
          
            


           float3 dir   = PARTICLES[id.x].position - PARTICLES[pIDX].position ;
            if(dot(dir,dir) > pow(SMOOTHING_RADIUS,1)) continue;
            //float3 edgeDistance = HALF_BOUNDSIZE - abs(PARTICLES[id.x].position.x);

            dir = (sqrt(dot(dir,dir)) > 0) ? dir: float3(0,1,0); 
           float  dist  = sqrt(dot(dir,dir));
           if(dist >SMOOTHING_RADIUS) continue;


           float3 dirNormalized = dir/dist;

           float pressureMean =  (PARTICLES[id.x].pressure + PARTICLES[pIDX].pressure)/2.0f;

           


           pressureForce    += (PARTICLES[pIDX].mass/PARTICLES[pIDX].density) * pressureMean * SpikeyKernelFirstDerivative(dist, pow(SMOOTHING_RADIUS,1),pi) * dirNormalized;
          
           viscosityForce   += (PARTICLES[pIDX].velocity - PARTICLES[id.x].velocity) * ViscosityKernelLaplacian(dist,SMOOTHING_RADIUS);

           






        }

    }


        // Boundary Forces particle stencil:

        

   


        
        float3 edgeDistance = (HALF_BOUNDSIZE - PARTICLE_RADIUS ) - abs(position);
        float3 normalED = edgeDistance/SMOOTHING_RADIUS;

        normalED.x *= sign(position.x);
        normalED.y *= sign(position.y);
        normalED.z *= sign(position.z);

        
    // if(IsWallHit(normalED))
    // {
    //     for(int i = 0; i<v_ParticleNumber;i++)
    //     {
    //         float3 vPoint = TranslatePoint(vPARTICLES[i], PARTICLES[id.x].predictedPosition);

    //         float3 dstToPoint = (vPoint - PARTICLES[id.x].predictedPosition);

    //         if(     (normalED.x < dstToPoint.x && normalED.x < SMOOTHING_RADIUS)||
    //                 (normalED.y < dstToPoint.y && normalED.y < SMOOTHING_RADIUS)||
    //                 (normalED.z < dstToPoint.z && normalED.z < SMOOTHING_RADIUS)){

    //                  PARTICLES[id.x].color = float3(1,1,0);
    //                  float3 dir   = PARTICLES[id.x].predictedPosition - vPoint ;
    //                 if(dot(dir,dir) > pow(SMOOTHING_RADIUS,1)) continue;
    //         //float3 edgeDistance = HALF_BOUNDSIZE - abs(PARTICLES[id.x].position.x);

    //                 dir = (sqrt(dot(dir,dir)) > 0) ? dir: float3(0,1,0); 
    //                 float  dist  = sqrt(dot(dir,dir));
    //                 if(dist >SMOOTHING_RADIUS) continue;


    //                 float3 dirNormalized = dir/dist;

    //                 float pressureMean =  (PARTICLES[id.x].pressure + PARTICLES[id.x].pressure)/2.0f;

    //                  pressureForce    += (PARTICLES[id.x].mass/1000.0f) * pressureMean * SpikeyKernelFirstDerivative(dstToPoint, pow(SMOOTHING_RADIUS,1),pi) * dirNormalized;
          
    //                 viscosityForce   += ( - PARTICLES[id.x].velocity) * ViscosityKernelLaplacian(dstToPoint,SMOOTHING_RADIUS);
                    
                    
    //                 }
    //     }
    // }

        

        float3 repulsionForce = sign(position)*normalED*EPSILON; ;

        float3 q = abs(position) - HALF_BOUNDSIZE;
        float  l = length(max(q,0.0)) + min(max(q.x,max(q.y,q.z)),0.0);

        float3 LJ_force = LennardJonesForce(length(edgeDistance),EPSILON,SMOOTHING_RADIUS*2.0f,PARTICLES[id.x].mass);
        //float3 boundaryRepForce = CalculateBoundaryForce(PARTICLES[id.x].predictedPosition,-HALF_BOUNDSIZE,HALF_BOUNDSIZE, SMOOTHING_RADIUS,10000.0f); 
        PARTICLES[id.x].offset =  -(pressureForce/PARTICLES[id.x].density) + VISCOSITY*viscosityForce ;

        float repulsionDistanceFactor = (length(edgeDistance)/SMOOTHING_RADIUS >= 1) ? 0: length(edgeDistance)/SMOOTHING_RADIUS;
        
            PARTICLES[id.x].offset += repulsionForce * repulsionDistanceFactor;
            PARTICLES[id.x].color = normalize(repulsionForce) + 0.5f;
        
        //if(length(PARTICLES[id.x].offset) > fMax) fMax = length(PARTICLES[id.x].offset);
       

        


}

[numthreads(GROUP_SIZE,1,1)]
void Update (uint3 id : SV_DispatchThreadID)
{

    if(PARTICLES[id.x]._static ==1)
    {
        return;
    }
    // TODO: insert actual code here!
    if(id.x >= NUMBER_OF_PARTICLES) return; 
    
    
   
    float3 position = PARTICLES[id.x].position;
     float timestep = 0.001f;

    float3 velocity = PARTICLES[id.x].velocity;
   
    // ********************** Adaptive Time Stepping ********************************
    //if(length(PARTICLES[id.x].velocity) > vMax) vMax = length(PARTICLES[id.x].velocity);
    //   float cfl = 0.004*(SMOOTHING_RADIUS/sqrt(STIFFNESS));
    //   float dTF = 0.00025*sqrt(SMOOTHING_RADIUS/fMax);
    // float timestep = min(cfl,dTF);
    // timestep = min(DT/2.0f,timestep);
    
   
   
    float3 pressureForce =  (PARTICLES[id.x].offset)*timestep;

   
     

     for(int i = 0; i<10; i++)
     {

        //VerletIntegration(PARTICLES[id.x].position,position,velocity,pressureForce,timestep);
        //velocity = velocity +pressureForce + GRAVITY/1.0f*timestep ;
        //  position = PARTICLES[id.x].position + velocity * timestep;

        //EulerIntegration(PARTICLES[id.x].position,position, velocity,pressureForce,timestep);
        //VerletIntegration(PARTICLES[id.x].position,position,velocity,pressureForce,timestep);
         SemiImplicitEuler(position,velocity,pressureForce,timestep);
    

     
     }
     
     
     //SemiImplicitEuler(position,velocity,pressureForce,timestep*10.0f);
     //velocity += AddBoundaryRepulsion(position,1000.0f,PARTICLE_RADIUS*2.0f,PARTICLES[id.x].mass)*timestep;
     //EulerIntegration(PARTICLES[id.x].position,position, velocity,pressureForce,timestep*10.0f);
     //LeapfrogIntegrator(position, velocity,pressureForce,timestep*10.0f);
     //VerletIntegration(PARTICLES[id.x].position,position,velocity,pressureForce,timestep*50.0f);

     
     stats[0] = vMax;
     stats[1] = fMax;
     stats[2] = maxPressure;
    

     int iterations = 0;
     //MembraneCollisions_Felix(id,position,velocity,timestep);
     while(iterations < 4)
     {

  
        float travelDistance = length(position - PARTICLES[id.x].position);

        Ray ray = ConstructRay(position, normalize(velocity), travelDistance );
        HitInfo info = GetHitInfo();
        //bool hit = ResolveMeshCollisions(ray, info);
        bool hit = BruteForceCollisions(id,PARTICLES,velocity,position,timestep*10.0f,info);

        int nodeIndex_root;
        int nodeIndex_tip;


     

        bool hit_root   = CheckBVHCollisions(ray,nodeIndex_root);
        bool hit_tip    = CheckBVHCollisions(InvertRay(ray),nodeIndex_tip);

    

        PARTICLES[id.x].color = (hit) ? float3(1,0,0):float3(0,0,0);

        if(hit_root && !hit_tip)  PARTICLES[id.x].color = float3(1,1,0);
        if(hit_tip && !hit_root)   PARTICLES[id.x].color = float3(0,1,1);
        if(hit_tip && hit_root)   PARTICLES[id.x].color = float3(0,1,0);


    
        bool  exceedsRadius     = travelDistance >= 2*PARTICLE_RADIUS;
        PARTICLES[id.x].color = (hit) ? float3(1,1,0):float3(0,0,0);


        if(hit)
        {

            //bool collision = BVHGeometryCollisions(id, PARTICLES,nodeIndex_root,velocity,position,timestep,info);
            
            if(hit)
            {
                //PARTICLES[id.x].color = float3(0,0,1);

                float dot_v_n = dot(normalize(velocity),info.normal);
                bool isInside =  dot_v_n > 0.0f;
                velocity = (!isInside) ? reflect(velocity,info.normal)*0.9f:velocity;

                
                velocity = reflect(velocity,info.normal)*0.55f;
                position = info.hitPoint + info.normal*1.5f* PARTICLE_RADIUS;



            }
        }

        iterations++;
        
        }

    


     ResolveCollisions(position,velocity,id.x);
    
    //PARTICLES[id.x].color = float3(PARTICLES[id.x].type/100,0,1- (PARTICLES[id.x].type/100));
     
   

   
    
}


    [numthreads(8,1,1)]
void ConstraintSolver (uint3 id : SV_DispatchThreadID)
{

   
   
    // Will loop over a ConstraintBuffer and solve the constraints.
    // Needs:   PARTICLES, CONSTRAINTS,
    // That should be it.

       

    

}


